name: version-updater
run-name: ${{ github.actor }} updating version
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: run without updating version for testing purposes
        required: true
        default: false
        type: boolean
      update_level:
        description: the version to update to
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
jobs:
  update-version:
    runs-on: ubuntu-latest
    env:
      DRY_RUN: ${{ inputs.dry_run }}
    steps:
      - name: checkout master step
        uses: actions/checkout@v3
        with:
          ref: master
      - name: set current version
        run: echo "CURRENT_VERSION=$(bash ./version_updater.bash set_current_version)" >> $GITHUB_ENV
      - name: checkout original branch ${{ github.ref_name }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - name: update versions
        run: bash ./version_updater.bash update ${{ inputs.update_level }}
        env:
          CURRENT_REF_NAME: ${{ github.ref_name }}
      - name: Add & Commit updated files
        uses: EndBug/add-and-commit@v9.1.3
        with:
          add: "['package-lock.json', 'package.json', 'static/manifest.json']"
          message: 'version update to $NEW_VERSION'
