name: version-updater
run-name: ${{ github.actor }} updating version
on:
  pull_request:
    types: [opened, edited]
    branches:
      - master
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: chmod u+x version-updater.bash
      - run: ./version_updater.bash 0
