name: version-updater
run-name: ${{ github.actor }} updating version
on:
  workflow_dispatch:
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master step
        uses: actions/checkout@v3
        with:
          ref: master
      - name: set current version
        run: echo "CURRENT_VERSION=$(bash ./version_updater.bash set_current_version)" >> $GITHUB_ENV
      - name: checkout original branch ${{ github.sha }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - name: update versions
        run: bash ./version_updater.bash update 0
        env:
          CURRENT_REF_NAME: ${{ github.ref_name }}
      - name: Add & Commit updated files
        uses: EndBug/add-and-commit@v9.1.3
        with:
          add: "['package-lock.json', 'package.json', 'static/manifest.json']"
          message: 'version update'
