name: version-updater
run-name: ${{ github.actor }} updating version
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited]
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: bash ./version_updater.bash 0
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.3
        with:
          add: "['package-lock.json', 'package.json', 'static/manifest.json']"
          message: 'version update'
